# Generated by Django 3.0.7 on 2021-12-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0015_auto_20211014_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Primary_Tech_Experience',
            new_name='Level',
        ),
    ]
